name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yaml
  tests:
    uses: ./.github/workflows/tests.yaml
  release:
    name: Release
    needs: [pre-commit, tests]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv and sync dev dependencies
        run: |
          pip install uv
          uv venv
          echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV
          echo "$PWD/.venv/bin" >> $GITHUB_PATH
          uv sync --dev

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: semantic-release publish
